id: 8942af69491842b28097c3417703b5d8
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_97-The_Chapter_on_Manjusri%E2%80%99s_Magical_Display-v1
  language: bo
  author: ''
  volume: {}
